[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/musicians"
  to = "/.netlify/functions/musicians"
  status = 200

[[redirects]]
  from = "/api/update"
  to = "/.netlify/functions/update"
  status = 200
